// Random game data that is added to Firestore
// After you've signed into GameVault, click the dropdown
// menu in the top right corner and select "Add random data"

export const randomData = {
  gameTitles: [
    "Elden Ring",
    "God of War Ragnarök",
    "The Legend of Zelda: Tears of the Kingdom",
    "Cyberpunk 2077",
    "Hollow Knight",
    "Starfield",
    "The Witcher 3: Wild Hunt",
    "Red Dead Redemption 2",
    "Dark Souls III",
    "Sekiro: Shadows Die Twice",
    "Bloodborne",
    "Ghost of Tsushima",
    "Horizon Zero Dawn",
    "The Last of Us Part II",
    "Spider-Man",
    "Uncharted 4: A Thief's End",
    "God of War",
    "Breath of the Wild",
    "Super Mario Odyssey",
    "Animal Crossing: New Horizons",
  ],
  gameGenres: [
    "Action RPG",
    "Adventure",
    "Shooter",
    "Platformer",
    "Open World",
    "Strategy",
    "RPG",
    "Fighting",
    "Racing",
    "Puzzle",
    "Horror",
    "Simulation",
    "Sports",
    "Stealth",
  ],
  gamePlatforms: ["PC", "PlayStation 5", "Xbox Series X", "Nintendo Switch", "PlayStation 4", "Xbox One"],
  gameDevelopers: [
    "FromSoftware",
    "Nintendo",
    "CD Projekt Red",
    "Santa Monica Studio",
    "Bethesda Game Studios",
    "Rockstar Games",
    "Valve",
    "Naughty Dog",
    "Sucker Punch Productions",
    "Guerrilla Games",
    "Insomniac Games",
    "Capcom",
    "Square Enix",
    "Ubisoft",
    "Electronic Arts",
  ],
  gameReviews: [
    { rating: 5, text: "Absolutely stunning game with deep lore and incredible gameplay." },
    { rating: 4, text: "Beautiful graphics and great gameplay mechanics." },
    { rating: 3, text: "Fun but could use more content and polish." },
    { rating: 5, text: "A must-play for any gamer! Masterpiece of storytelling." },
    { rating: 4, text: "Fantastic soundtrack and visuals, engaging combat." },
    { rating: 2, text: "Buggy performance on launch, needs more optimization." },
    { rating: 5, text: "Incredible world design and attention to detail." },
    { rating: 4, text: "Great story and characters, some technical issues." },
    { rating: 3, text: "Decent game but lacks innovation in the genre." },
    { rating: 5, text: "Perfect blend of action and exploration." },
    { rating: 4, text: "Solid gameplay with beautiful art direction." },
    { rating: 2, text: "Disappointing compared to previous entries." },
  ],
};
